model_name_or_path: "deepseek-coder-1.3b-instruct"
ckpt_path: "/nvme/hf_models/deepseek-coder-1.3b-instruct/pytorch_model.bin"
load_model_state_dict: False
use_position: null

tokenizer_name_or_path: "deepseek-coder-1.3b-instruct"
