model_name_or_path: "mamba-370m-hf"
tokenizer_name_or_path: "mamba-370m-hf"
ckpt_path: "mamba-370m-hf/pytorch_model.bin"
use_custom_module: True
load_model_state_dict: False
use_relative_position: False
use_abs_position: False
max_position_embeddings: 16384
custom_conv1d: True
conv1d_configs:
  kernel_sizes: 16

