dataset:
  data_path: "needle/PaulGrahamEssays/*.txt"
  processed_data_path: "needle/processed_data/128k_500_insert_ids.pkl"
  max_seq_length: 128000
  module: 'custom_dataset.passkey_search' # Custom dataset module path
  class_name: 'PasskeySearchDataset'  # dataset class name
  depth: 0.5
  key: "The best thing to do in San Francisco is"
  value: "eat a sandwich and sit in Dolores Park on a sunny day."
  nworkers: 12
  pin_memory: False
  inference_mode: True
  cluster_batch: False

other_cfgs: 
  max_generation_length: 48
  testing_max_ctx: 128000

inference_cfg:
  save_keys: ['depth', 'ctx_length', 'real_length']


  
