dataset:
  data_path: "/nvme/zecheng/data/slimpajama-per-source-length-upsample-gpt-hf"
  processed_data_path: null
  split: null
  module: 'custom_dataset.simplepajama' # Custom dataset module path
  class_name: 'SimplepajamaDataset'  # dataset class name
  max_seq_length: 4200
  nworkers: 2
  train_batch_size: 1
  val_batch_size: 1
  pin_memory: False
  inference_mode: False
  cluster_batch: True
  require_process: False

other_cfgs: null

  
